//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV607_W2_Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class actions {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal actions() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV607_W2_Design.Properties.actions", typeof(actions).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Add Boat.
        /// </summary>
        internal static string actionAddBoat {
            get {
                return ResourceManager.GetString("actionAddBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Create New Member.
        /// </summary>
        internal static string actionCreateMember {
            get {
                return ResourceManager.GetString("actionCreateMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.Delete Boat.
        /// </summary>
        internal static string actionDeleteBoat {
            get {
                return ResourceManager.GetString("actionDeleteBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.Delete Member.
        /// </summary>
        internal static string actionDeleteMember {
            get {
                return ResourceManager.GetString("actionDeleteMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 3.Edit Boat.
        /// </summary>
        internal static string actionEditBoat {
            get {
                return ResourceManager.GetString("actionEditBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 2.Edit Member.
        /// </summary>
        internal static string actionEditMember {
            get {
                return ResourceManager.GetString("actionEditMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.Edit Member Info.
        /// </summary>
        internal static string actionEditMemberInfo {
            get {
                return ResourceManager.GetString("actionEditMemberInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0.Quit.
        /// </summary>
        internal static string actionQuit {
            get {
                return ResourceManager.GetString("actionQuit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5.View Compact list.
        /// </summary>
        internal static string actionViewCompact {
            get {
                return ResourceManager.GetString("actionViewCompact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4.View Member.
        /// </summary>
        internal static string actionViewMember {
            get {
                return ResourceManager.GetString("actionViewMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 6.View Verbose list.
        /// </summary>
        internal static string actionViewVerbose {
            get {
                return ResourceManager.GetString("actionViewVerbose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string String1 {
            get {
                return ResourceManager.GetString("String1", resourceCulture);
            }
        }
    }
}
