//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace _1DV607_W2_Design.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("_1DV607_W2_Design.Properties.messages", typeof(messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boat created!.
        /// </summary>
        internal static string boatCreated {
            get {
                return ResourceManager.GetString("boatCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose action with number keys.
        /// </summary>
        internal static string chooseAction {
            get {
                return ResourceManager.GetString("chooseAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose boat using number keys.
        /// </summary>
        internal static string chooseBoat {
            get {
                return ResourceManager.GetString("chooseBoat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose member using number keys.
        /// </summary>
        internal static string chooseMember {
            get {
                return ResourceManager.GetString("chooseMember", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compact View.
        /// </summary>
        internal static string compactStr {
            get {
                return ResourceManager.GetString("compactStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter first name..
        /// </summary>
        internal static string firstNameInput {
            get {
                return ResourceManager.GetString("firstNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please input length [in feet].
        /// </summary>
        internal static string inputLength {
            get {
                return ResourceManager.GetString("inputLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid input:.
        /// </summary>
        internal static string invalidInput {
            get {
                return ResourceManager.GetString("invalidInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter last name..
        /// </summary>
        internal static string lastNameInput {
            get {
                return ResourceManager.GetString("lastNameInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member deleted.
        /// </summary>
        internal static string membeDeleted {
            get {
                return ResourceManager.GetString("membeDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Index does not exist..
        /// </summary>
        internal static string nonExistantIndex {
            get {
                return ResourceManager.GetString("nonExistantIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not a number..
        /// </summary>
        internal static string notNumber {
            get {
                return ResourceManager.GetString("notNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Personal Number. [YYYYMMDD-XXXX].
        /// </summary>
        internal static string pNumberInput {
            get {
                return ResourceManager.GetString("pNumberInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press r to return.
        /// </summary>
        internal static string returnStr {
            get {
                return ResourceManager.GetString("returnStr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify the type of boat..
        /// </summary>
        internal static string specBoatType {
            get {
                return ResourceManager.GetString("specBoatType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please specify boat type..
        /// </summary>
        internal static string specType {
            get {
                return ResourceManager.GetString("specType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verbose View.
        /// </summary>
        internal static string verboseStr {
            get {
                return ResourceManager.GetString("verboseStr", resourceCulture);
            }
        }
    }
}
